[2024-09-04T01:59:49.386+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T01:59:49.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T01:59:49.437+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T01:59:49.437+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-04T01:59:49.530+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_KPI_theo_nam> on 2024-09-03 00:00:00+00:00
[2024-09-04T01:59:49.553+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=181) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T01:59:49.552+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_KPI_theo_nam', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmp7rx53ram']
[2024-09-04T01:59:49.555+0000] {standard_task_runner.py:64} INFO - Started process 204 to run task
[2024-09-04T01:59:49.555+0000] {standard_task_runner.py:91} INFO - Job 127: Subtask import_csv_KPI_theo_nam
[2024-09-04T01:59:49.580+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T01:59:49.635+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam scheduled__2024-09-03T00:00:00+00:00 [running]> on host 7932644bd5dc
[2024-09-04T01:59:50.081+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_KPI_theo_nam' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T01:59:50.082+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T01:59:50.126+0000] {logging_mixin.py:188} INFO - Error inserting data into table KPI_theo_nam: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-04T01:59:50.127+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-04T01:59:50.129+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T01:59:50.138+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_KPI_theo_nam, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T015949, end_date=20240904T015950
[2024-09-04T01:59:50.213+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-04T01:59:50.231+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T01:59:50.233+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-04T02:58:07.672+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T02:58:07.741+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T02:58:07.765+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T02:58:07.765+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-04T02:58:07.806+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_KPI_theo_nam> on 2024-09-03 00:00:00+00:00
[2024-09-04T02:58:07.845+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_KPI_theo_nam', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpss0s8vaw']
[2024-09-04T02:58:07.846+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1382) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T02:58:07.851+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask import_csv_KPI_theo_nam
[2024-09-04T02:58:07.852+0000] {standard_task_runner.py:64} INFO - Started process 1407 to run task
[2024-09-04T02:58:07.897+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T02:58:07.984+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam scheduled__2024-09-03T00:00:00+00:00 [running]> on host f537b9e2448c
[2024-09-04T02:58:09.042+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_KPI_theo_nam' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T02:58:09.043+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T02:58:09.089+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-09-04T02:58:09.115+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T02:58:09.117+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/import_csv_to_mysql_dag.py", line 95, in import_csv_to_mysql
    create_table_if_not_exists(engine, table_name, df)
  File "/opt/airflow/dags/import_csv_to_mysql_dag.py", line 78, in create_table_if_not_exists
    if table_name not in inspector.get_table_names():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 266, in get_table_names
    return self.dialect.get_table_names(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get_table_names
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2801, in get_table_names
    % self.identifier_preparer.quote_identifier(current_schema)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 5352, in quote_identifier
    + self._escape_identifier(value)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 5311, in _escape_identifier
    value = value.replace(self.escape_quote, self.escape_to_quote)
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-09-04T02:58:09.143+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=import_csv_to_mysql, task_id=import_csv_KPI_theo_nam, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T025807, end_date=20240904T025809
[2024-09-04T02:58:09.163+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task import_csv_KPI_theo_nam ('NoneType' object has no attribute 'replace'; 1407)
[2024-09-04T02:58:09.210+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-04T02:58:09.240+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T02:58:09.243+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
