[2024-09-04T01:59:49.382+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T01:59:49.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T01:59:49.433+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T01:59:49.434+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-04T01:59:49.462+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_Nhan_vien> on 2024-09-03 00:00:00+00:00
[2024-09-04T01:59:49.476+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_Nhan_vien', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmprg0n9avk']
[2024-09-04T01:59:49.478+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=186) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T01:59:49.479+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask import_csv_Nhan_vien
[2024-09-04T01:59:49.479+0000] {standard_task_runner.py:64} INFO - Started process 199 to run task
[2024-09-04T01:59:49.499+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T01:59:49.572+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien scheduled__2024-09-03T00:00:00+00:00 [running]> on host 7932644bd5dc
[2024-09-04T01:59:50.036+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_Nhan_vien' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T01:59:50.037+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T01:59:50.078+0000] {logging_mixin.py:188} INFO - Error inserting data into table Nhan_vien: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-04T01:59:50.080+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-04T01:59:50.081+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T01:59:50.090+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_Nhan_vien, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T015949, end_date=20240904T015950
[2024-09-04T01:59:50.140+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-04T01:59:50.160+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T01:59:50.162+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-04T02:58:07.674+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T02:58:07.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T02:58:07.764+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T02:58:07.766+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-04T02:58:07.818+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_Nhan_vien> on 2024-09-03 00:00:00+00:00
[2024-09-04T02:58:07.847+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1378) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T02:58:07.855+0000] {standard_task_runner.py:64} INFO - Started process 1413 to run task
[2024-09-04T02:58:07.855+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_Nhan_vien', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpo_in87b2']
[2024-09-04T02:58:07.860+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask import_csv_Nhan_vien
[2024-09-04T02:58:07.895+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T02:58:07.983+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien scheduled__2024-09-03T00:00:00+00:00 [running]> on host f537b9e2448c
[2024-09-04T02:58:09.023+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_Nhan_vien' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T02:58:09.025+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T02:58:09.067+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-09-04T02:58:09.088+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T02:58:09.090+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/import_csv_to_mysql_dag.py", line 95, in import_csv_to_mysql
    create_table_if_not_exists(engine, table_name, df)
  File "/opt/airflow/dags/import_csv_to_mysql_dag.py", line 78, in create_table_if_not_exists
    if table_name not in inspector.get_table_names():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 266, in get_table_names
    return self.dialect.get_table_names(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get_table_names
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2801, in get_table_names
    % self.identifier_preparer.quote_identifier(current_schema)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 5352, in quote_identifier
    + self._escape_identifier(value)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 5311, in _escape_identifier
    value = value.replace(self.escape_quote, self.escape_to_quote)
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-09-04T02:58:09.120+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=import_csv_to_mysql, task_id=import_csv_Nhan_vien, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T025807, end_date=20240904T025809
[2024-09-04T02:58:09.142+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task import_csv_Nhan_vien ('NoneType' object has no attribute 'replace'; 1413)
[2024-09-04T02:58:09.201+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-04T02:58:09.224+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
