[2024-09-04T01:59:49.382+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T01:59:49.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Chi_nhanh scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T01:59:49.434+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Chi_nhanh scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T01:59:49.434+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-04T01:59:49.471+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_Chi_nhanh> on 2024-09-03 00:00:00+00:00
[2024-09-04T01:59:49.485+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T01:59:49.486+0000] {standard_task_runner.py:64} INFO - Started process 200 to run task
[2024-09-04T01:59:49.485+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_Chi_nhanh', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmp1s5zggsn']
[2024-09-04T01:59:49.488+0000] {standard_task_runner.py:91} INFO - Job 125: Subtask import_csv_Chi_nhanh
[2024-09-04T01:59:49.505+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T01:59:49.581+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_Chi_nhanh scheduled__2024-09-03T00:00:00+00:00 [running]> on host 7932644bd5dc
[2024-09-04T01:59:50.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_Chi_nhanh' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T01:59:50.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T01:59:50.078+0000] {logging_mixin.py:188} INFO - Error inserting data into table Chi_nhanh: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-04T01:59:50.080+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-04T01:59:50.081+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T01:59:50.090+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_Chi_nhanh, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T015949, end_date=20240904T015950
[2024-09-04T01:59:50.143+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-04T01:59:50.154+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-04T02:58:07.671+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T02:58:07.741+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Chi_nhanh scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T02:58:07.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Chi_nhanh scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T02:58:07.763+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-04T02:58:07.807+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_Chi_nhanh> on 2024-09-03 00:00:00+00:00
[2024-09-04T02:58:07.840+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1384) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T02:58:07.845+0000] {standard_task_runner.py:64} INFO - Started process 1411 to run task
[2024-09-04T02:58:07.846+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_Chi_nhanh', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpissqn9om']
[2024-09-04T02:58:07.854+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask import_csv_Chi_nhanh
[2024-09-04T02:58:07.893+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T02:58:07.978+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_Chi_nhanh scheduled__2024-09-03T00:00:00+00:00 [running]> on host f537b9e2448c
[2024-09-04T02:58:09.047+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_Chi_nhanh' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T02:58:09.050+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T02:58:09.097+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-09-04T02:58:09.121+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T02:58:09.122+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/import_csv_to_mysql_dag.py", line 95, in import_csv_to_mysql
    create_table_if_not_exists(engine, table_name, df)
  File "/opt/airflow/dags/import_csv_to_mysql_dag.py", line 78, in create_table_if_not_exists
    if table_name not in inspector.get_table_names():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 266, in get_table_names
    return self.dialect.get_table_names(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get_table_names
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2801, in get_table_names
    % self.identifier_preparer.quote_identifier(current_schema)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 5352, in quote_identifier
    + self._escape_identifier(value)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 5311, in _escape_identifier
    value = value.replace(self.escape_quote, self.escape_to_quote)
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-09-04T02:58:09.146+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=import_csv_to_mysql, task_id=import_csv_Chi_nhanh, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T025807, end_date=20240904T025809
[2024-09-04T02:58:09.168+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task import_csv_Chi_nhanh ('NoneType' object has no attribute 'replace'; 1411)
[2024-09-04T02:58:09.199+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-04T02:58:09.227+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T02:58:09.229+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
