[2024-09-03T09:50:30.818+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T09:50:30.846+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_Khach_hang manual__2024-09-03T09:49:20.042457+00:00 [queued]>
[2024-09-03T09:50:30.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_Khach_hang manual__2024-09-03T09:49:20.042457+00:00 [queued]>
[2024-09-03T09:50:30.856+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-09-03T09:50:30.876+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_Khach_hang> on 2024-09-03 09:49:20.042457+00:00
[2024-09-03T09:50:30.887+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3810) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-03T09:50:30.889+0000] {standard_task_runner.py:64} INFO - Started process 3823 to run task
[2024-09-03T09:50:30.888+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_Khach_hang', 'manual__2024-09-03T09:49:20.042457+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/first_task.py', '--cfg-path', '/tmp/tmpgcv34t8h']
[2024-09-03T09:50:30.891+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask import_Khach_hang
[2024-09-03T09:50:30.909+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-03T09:50:30.936+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_Khach_hang manual__2024-09-03T09:49:20.042457+00:00 [running]> on host 6f6575553fe4
[2024-09-03T09:50:31.312+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_Khach_hang' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T09:49:20.042457+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T09:49:20.042457+00:00'
[2024-09-03T09:50:31.313+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T09:50:31.326+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T09:50:31.327+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/import_csv.py", line 13, in import_csv_to_mysql
    data = pd.read_csv(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Intern\\Yeucau3\\Scheduler\\dags/Khach_hang.csv'
[2024-09-03T09:50:31.337+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=import_csv_to_mysql, task_id=import_Khach_hang, run_id=manual__2024-09-03T09:49:20.042457+00:00, execution_date=20240903T094920, start_date=20240903T095030, end_date=20240903T095031
[2024-09-03T09:50:31.355+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task import_Khach_hang ([Errno 2] No such file or directory: 'D:\\Intern\\Yeucau3\\Scheduler\\dags/Khach_hang.csv'; 3823)
[2024-09-03T09:50:31.384+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-03T09:50:31.393+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
