[2024-09-04T01:59:49.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T01:59:49.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_San_pham scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T01:59:49.434+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_San_pham scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T01:59:49.434+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-04T01:59:49.509+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_San_pham> on 2024-09-03 00:00:00+00:00
[2024-09-04T01:59:49.524+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_San_pham', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpfxrxflxl']
[2024-09-04T01:59:49.524+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=185) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T01:59:49.527+0000] {standard_task_runner.py:91} INFO - Job 126: Subtask import_csv_San_pham
[2024-09-04T01:59:49.528+0000] {standard_task_runner.py:64} INFO - Started process 203 to run task
[2024-09-04T01:59:49.569+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T01:59:49.634+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_San_pham scheduled__2024-09-03T00:00:00+00:00 [running]> on host 7932644bd5dc
[2024-09-04T01:59:50.091+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_San_pham' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T01:59:50.094+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T01:59:50.171+0000] {logging_mixin.py:188} INFO - Error inserting data into table San_pham: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-04T01:59:50.173+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-04T01:59:50.174+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T01:59:50.181+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_San_pham, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T015949, end_date=20240904T015950
[2024-09-04T01:59:50.229+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-04T01:59:50.246+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T01:59:50.248+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-04T02:58:07.675+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T02:58:07.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_San_pham scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T02:58:07.770+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_San_pham scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-09-04T02:58:07.771+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-04T02:58:07.835+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_San_pham> on 2024-09-03 00:00:00+00:00
[2024-09-04T02:58:07.868+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1385) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T02:58:07.870+0000] {standard_task_runner.py:64} INFO - Started process 1414 to run task
[2024-09-04T02:58:07.870+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_San_pham', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpiwbc6eaf']
[2024-09-04T02:58:07.873+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask import_csv_San_pham
[2024-09-04T02:58:07.911+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T02:58:08.010+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_San_pham scheduled__2024-09-03T00:00:00+00:00 [running]> on host f537b9e2448c
[2024-09-04T02:58:09.079+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_San_pham' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T00:00:00+00:00'
[2024-09-04T02:58:09.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T02:58:09.136+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-09-04T02:58:09.155+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T02:58:09.156+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/import_csv_to_mysql_dag.py", line 95, in import_csv_to_mysql
    create_table_if_not_exists(engine, table_name, df)
  File "/opt/airflow/dags/import_csv_to_mysql_dag.py", line 78, in create_table_if_not_exists
    if table_name not in inspector.get_table_names():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 266, in get_table_names
    return self.dialect.get_table_names(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get_table_names
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2801, in get_table_names
    % self.identifier_preparer.quote_identifier(current_schema)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 5352, in quote_identifier
    + self._escape_identifier(value)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/compiler.py", line 5311, in _escape_identifier
    value = value.replace(self.escape_quote, self.escape_to_quote)
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-09-04T02:58:09.184+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=import_csv_to_mysql, task_id=import_csv_San_pham, run_id=scheduled__2024-09-03T00:00:00+00:00, execution_date=20240903T000000, start_date=20240904T025807, end_date=20240904T025809
[2024-09-04T02:58:09.203+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task import_csv_San_pham ('NoneType' object has no attribute 'replace'; 1414)
[2024-09-04T02:58:09.253+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-04T02:58:09.271+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
