[2024-09-04T03:28:53.345+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-04T03:28:53.369+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: query_statement.mysql_to_hook manual__2024-09-04T03:28:51.359434+00:00 [queued]>
[2024-09-04T03:28:53.376+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: query_statement.mysql_to_hook manual__2024-09-04T03:28:51.359434+00:00 [queued]>
[2024-09-04T03:28:53.376+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-04T03:28:53.390+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): mysql_to_hook> on 2024-09-04 03:28:51.359434+00:00
[2024-09-04T03:28:53.398+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'query_statement', 'mysql_to_hook', 'manual__2024-09-04T03:28:51.359434+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/first_task.py', '--cfg-path', '/tmp/tmpf50d_p5_']
[2024-09-04T03:28:53.399+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=463) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-04T03:28:53.399+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask mysql_to_hook
[2024-09-04T03:28:53.400+0000] {standard_task_runner.py:64} INFO - Started process 465 to run task
[2024-09-04T03:28:53.411+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-04T03:28:53.432+0000] {task_command.py:426} INFO - Running <TaskInstance: query_statement.mysql_to_hook manual__2024-09-04T03:28:51.359434+00:00 [running]> on host 9927162d0e47
[2024-09-04T03:28:53.624+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='query_statement' AIRFLOW_CTX_TASK_ID='mysql_to_hook' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T03:28:51.359434+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-04T03:28:51.359434+00:00'
[2024-09-04T03:28:53.625+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-04T03:28:53.638+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-09-04T03:28:53.645+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-04T03:28:53.646+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_task.py", line 30, in mysql_to_hook
    cursor.execute("select * from bai_test.hpg")
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'bai_test.hpg' doesn't exist")
[2024-09-04T03:28:53.653+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=query_statement, task_id=mysql_to_hook, run_id=manual__2024-09-04T03:28:51.359434+00:00, execution_date=20240904T032851, start_date=20240904T032853, end_date=20240904T032853
[2024-09-04T03:28:53.664+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task mysql_to_hook ((1146, "Table 'bai_test.hpg' doesn't exist"); 465)
[2024-09-04T03:28:53.694+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-04T03:28:53.704+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-04T03:28:53.705+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
